apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    typeName: Prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://prometheus:9090
    jsonData:
      httpMethod: GET

